# see: https://pre-commit.com/hooks.html

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - --autofix
      - id: trailing-whitespace
      # by default both master & main are prevented for committing to
#      - id: no-commit-to-branch
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v0.8.2
    hooks:
    - id: go-fmt
      args: ["-s", "-w"]
    - id: go-imports
      args: ["-w", "-local", "github.com/nmiculinic"]
