---
want:
  - 1password
  - ansible
  - aws-cli
  - aws-iam-authenticator-bin
  - bash-completion
  - bat
  - bfg
  - bind
  - bloomrpc
  - buf-bin
  - bwm-ng
  - calibre
  - cantata
  - ccid
  - cdrdao
  - cloc
  - dart
  - docker
  - docker-compose
  - dvd+rw-tools
  - emovix
  - etcher-bin
  - fail2ban
  - fd
  - fwupd
  - fzf
  - git-crypt
  - git-extras
  - go
  - goimports-git
  - golangci-lint-bin
  - google-chrome
  - google-cloud-sdk
  - gparted
  - graphviz
  - helm
  - hexyl
  - hibernator
  - insomnia-bin
  - iperf
  - jetbrains-toolbox
  - kernel-alive
  - kind-bin
  - kubectl
  - kustomize
  - lens-bin
  - libktorrent
  - libreoffice-fresh
  - logcli
  - minio
  - mosh
  - mpd
  - ncdu
  - neovim
  - net-tools
  - noto-fonts-cjk
  - noto-fonts-emoji
  - opensc
  - pacutils
  - podman
  - postgresql
  - python-pillow
  - python-pip
  - python-pyfuse3
  - python-pynvim
  - python-pysmbc
  - python-reportlab
  - qbittorrent
  - rancher-k3d-bin
  - restic
  - ripgrep
  - rust
  - skopeo
  - slack-desktop
  - steam-manjaro
  - strace
  - syncthing-bin
  - sysdig
  - sysstat
  - tailscale
  - terraform
  - timeshift
  - tmux
  - transcode
  - ttf-droid
  - ttf-inconsolata
  - ttf-indic-otf
  - ttf-liberation
  - ufw
  - vault
  - vcdimager
  - visual-studio-code-bin
  - vlc
  - wireguard-tools
  - wl-clipboard
  - xclip
  - xsel
  - yarn
  - yay
  - yq
ignore:
  - wallpapers-2018
  - wallpapers-juhraya
  - system-config-printer
  - systemd-boot-manager
  - a52dec
  - aalib
  - snapd
  - snapd-glib
  - accounts-qml-module
  - accountsservice
  - acl
  - acpi
  - acpid
  - adobe-source-code-pro-fonts
  - adobe-source-han-sans-cn-fonts
  - adobe-source-han-sans-jp-fonts
  - adobe-source-han-sans-kr-fonts
  - adobe-source-sans-pro-fonts
  - adwaita-icon-theme
  - alsa-card-profiles
  - alsa-firmware
  - alsa-lib
  - alsa-oss
  - alsa-plugins
  - alsa-topology-conf
  - alsa-ucm-conf
  - alsa-utils
  - amd-ucode
  - android-tools
  - android-udev
  - aom
  - appstream
  - appstream-glib
  - appstream-qt
  - archlinux-appstream-data
  - archlinux-keyring
  - argon2
  - ark
  - asciidoc
  - atk
  - at-spi2-atk
  - at-spi2-core
  - attica
  - attr
  - audit
  - avahi
  - b43-fwcutter
  - baloo
  - baloo-widgets
  - bash
  - bashrc-manjaro
  - bc
  - bluedevil
  - bluez
  - bluez-libs
  - bluez-qt
  - boost-libs
  - breath2-icon-themes
  - breath2-wallpaper
  - breeze
  - breeze-icons
  - brotli
  - btrfs-progs
  - bubblewrap
  - bzip2
  - ca-certificates
  - ca-certificates-mozilla
  - ca-certificates-utils
  - cairo
  - cantarell-fonts
  - cdparanoia
  - ceph-libs
  - cfitsio
  - chromaprint
  - cifs-utils
  - ckbcomp
  - colord
  - confuse
  - convertlit
  - coreutils
  - cpupower
  - crda
  - cronie
  - cryptsetup
  - curl
  - dav1d
  - db
  - dbus
  - dbus-glib
  - dbus-python
  - dconf
  - ddcutil
  - desktop-file-utils
  - device-mapper
  - dhclient
  - dhcpcd
  - diffutils
  - ding-libs
  - discount
  - djvulibre
  - dmidecode
  - dmraid
  - dnsmasq
  - dnssec-anchors
  - docbook-xml
  - docbook-xsl
  - dolphin
  - dolphin-plugins
  - dosfstools
  - double-conversion
  - e2fsprogs
  - ebook-tools
  - ecryptfs-utils
  - editorconfig-core-c
  - efibootmgr
  - efivar
  - exfat-utils
  - exiv2
  - expat
  - f2fs-tools
  - faac
  - faad2
  - ffmpeg
  - ffmpegthumbs
  - fftw
  - file
  - filesystem
  - findutils
  - firefox
  - flac
  - fluidsynth
  - fmt
  - fontconfig
  - frameworkintegration
  - freeglut
  - freetype2
  - fribidi
  - fuse2
  - fuse3
  - fuse-common
  - gawk
  - gcab
  - gcc-libs
  - gcr
  - gd
  - gdbm
  - gdk-pixbuf2
  - geoclue
  - geocode-glib
  - gettext
  - ghostscript
  - giflib
  - git
  - glew
  - glib2
  - glibc
  - glib-networking
  - glu
  - gmp
  - gnome-desktop
  - gnome-icon-theme
  - gnome-icon-theme-symbolic
  - gnome-keyring
  - gnome-themes-extra
  - gnupg
  - gnustep-base
  - gnutls
  - gobject-introspection-runtime
  - gpgme
  - gpm
  - gptfdisk
  - grantlee
  - graphene
  - graphite
  - grep
  - groff
  - grub
  - grub-theme-manjaro
  - gsettings-desktop-schemas
  - gsm
  - gssdp
  - gssproxy
  - gst-libav
  - gst-plugins-bad
  - gst-plugins-bad-libs
  - gst-plugins-base
  - gst-plugins-base-libs
  - gst-plugins-good
  - gst-plugins-ugly
  - gstreamer
  - gtk3
  - gtk-theme-breath
  - gtk-update-icon-cache
  - gupnp
  - gupnp-igd
  - gvfs
  - gvfs-afc
  - gvfs-gphoto2
  - gvfs-mtp
  - gvfs-nfs
  - gvfs-smb
  - gwenview
  - gzip
  - harfbuzz
  - haveged
  - hdparm
  - hicolor-icon-theme
  - hidapi
  - htop
  - http-parser
  - hunspell
  - hwids
  - hwinfo
  - hwloc
  - iana-etc
  - icu
  - ijs
  - illyria-wallpaper
  - imagemagick
  - imath
  - imlib2
  - inetutils
  - iniparser
  - intel-ucode
  - inxi
  - iproute2
  - iptables
  - iputils
  - iso-codes
  - iw
  - jack
  - jansson
  - jasper
  - jbig2dec
  - jfsutils
  - js78
  - json-c
  - json-glib
  - kaccounts-integration
  - kaccounts-providers
  - kactivities
  - kactivities-stats
  - kactivitymanagerd
  - kamera
  - karchive
  - kate
  - kauth
  - kbd
  - kbookmarks
  - kcalc
  - kcmutils
  - kcodecs
  - kcolorpicker
  - kcompletion
  - kconfig
  - kconfigwidgets
  - kcontacts
  - kcoreaddons
  - kcrash
  - kdbusaddons
  - kdeclarative
  - kde-cli-tools
  - kdeconnect
  - kdecoration
  - kded
  - kdegraphics-thumbnailers
  - kde-gtk-config
  - kdelibs4support
  - kdenetwork-filesharing
  - kdeplasma-addons
  - kdesu
  - kdnssd
  - kdoctools
  - kdsoap
  - kdsoap-ws-discovery-client
  - kemoticons
  - keyutils
  - kfilemetadata
  - kfind
  - kgamma5
  - kglobalaccel
  - kguiaddons
  - khelpcenter
  - kholidays
  - khotkeys
  - khtml
  - ki18n
  - kiconthemes
  - kidletime
  - kimageannotator
  - kimageformats
  - kinfocenter
  - kinit
  - kio
  - kio-extras
  - kirigami2
  - kitemmodels
  - kitemviews
  - kjobwidgets
  - kjs
  - kmenuedit
  - kmod
  - knewstuff
  - knotifications
  - knotifyconfig
  - konsole
  - konversation
  - kpackage
  - kparts
  - kpeople
  - kpeoplevcard
  - kpmcore
  - kpty
  - kquickcharts
  - krb5
  - krunner
  - kscreen
  - kscreenlocker
  - kservice
  - ksshaskpass
  - ksysguard
  - ksystemlog
  - ktexteditor
  - ktextwidgets
  - kunitconversion
  - kuserfeedback
  - kwallet
  - kwalletmanager
  - kwallet-pam
  - kwayland
  - kwayland-integration
  - kwayland-server
  - kwidgetsaddons
  - kwin
  - kwindowsystem
  - kwrited
  - kxmlgui
  - lame
  - lcms2
  - ldb
  - ldns
  - less
  - lib32-alsa-lib
  - lib32-bzip2
  - lib32-curl
  - lib32-dbus
  - lib32-e2fsprogs
  - lib32-expat
  - lib32-flac
  - lib32-gcc-libs
  - lib32-glew
  - lib32-glibc
  - lib32-glu
  - lib32-icu
  - lib32-keyutils
  - lib32-krb5
  - lib32-libasyncns
  - lib32-libcanberra
  - lib32-libcanberra-pulse
  - lib32-libcap
  - lib32-libdrm
  - lib32-libelf
  - lib32-libffi
  - lib32-libgcrypt
  - lib32-libglvnd
  - lib32-libgpg-error
  - lib32-libice
  - lib32-libidn2
  - lib32-libldap
  - lib32-libltdl
  - lib32-libnsl
  - lib32-libogg
  - lib32-libpciaccess
  - lib32-libpsl
  - lib32-libpulse
  - lib32-libsm
  - lib32-libsndfile
  - lib32-libssh2
  - lib32-libtirpc
  - lib32-libunistring
  - lib32-libunwind
  - lib32-libva
  - lib32-libva-intel-driver
  - lib32-libva-mesa-driver
  - lib32-libva-vdpau-driver
  - lib32-libvdpau
  - lib32-libvorbis
  - lib32-libx11
  - lib32-libxau
  - lib32-libxcb
  - lib32-libxcrypt
  - lib32-libxdamage
  - lib32-libxdmcp
  - lib32-libxext
  - lib32-libxfixes
  - lib32-libxi
  - lib32-libxml2
  - lib32-libxmu
  - lib32-libxshmfence
  - lib32-libxt
  - lib32-libxtst
  - lib32-libxxf86vm
  - lib32-llvm-libs
  - lib32-lm_sensors
  - lib32-mesa
  - lib32-mesa-demos
  - lib32-ncurses
  - lib32-openssl
  - lib32-opus
  - lib32-pam
  - lib32-readline
  - lib32-systemd
  - lib32-tdb
  - lib32-util-linux
  - lib32-vulkan-icd-loader
  - lib32-wayland
  - lib32-xz
  - lib32-zlib
  - lib32-zstd
  - libaccounts-glib
  - libaccounts-qt
  - libaio
  - libarchive
  - libass
  - libassuan
  - libasyncns
  - libatasmart
  - libavc1394
  - libavif
  - libavtp
  - libblockdev
  - libbluray
  - libbs2b
  - libbsd
  - libbytesize
  - libcaca
  - libcanberra
  - libcanberra-gstreamer
  - libcanberra-pulse
  - libcap
  - libcap-ng
  - libcddb
  - libcdio
  - libcdio-paranoia
  - libcloudproviders
  - libcroco
  - libcups
  - libdaemon
  - libdatrie
  - libdbusmenu-qt5
  - libdc1394
  - libdca
  - libde265
  - libdmtx
  - libdrm
  - libdv
  - libdvdcss
  - libdvdnav
  - libdvdread
  - libedit
  - libelf
  - libepoxy
  - libevdev
  - libevent
  - libexif
  - libfakekey
  - libfdk-aac
  - libffi
  - libfontenc
  - libftdi
  - libgcrypt
  - libgit2
  - libglvnd
  - libgme
  - libgpg-error
  - libgphoto2
  - libgudev
  - libgusb
  - libheif
  - libibus
  - libical
  - libice
  - libid3tag
  - libidn
  - libidn2
  - libiec61883
  - libimobiledevice
  - libinih
  - libinput
  - libinstpatch
  - libjpeg-turbo
  - libkate
  - libkdcraw
  - libkexiv2
  - libkipi
  - libksba
  - libkscreen
  - libksysguard
  - libldac
  - libldap
  - liblqr
  - liblrdf
  - libmad
  - libmbim
  - libmfx
  - libmicrodns
  - libmm-glib
  - libmms
  - libmng
  - libmnl
  - libmodplug
  - libmpcdec
  - libmpeg2
  - libmtp
  - libndp
  - libnetfilter_conntrack
  - libnewt
  - libnfnetlink
  - libnfs
  - libnftnl
  - libnghttp2
  - libnice
  - libnl
  - libnm
  - libnotify
  - libnsl
  - libofa
  - libogg
  - libomxil-bellagio
  - libopenaptx
  - libp11-kit
  - libpaper
  - libpcap
  - libpciaccess
  - libpgm
  - libpipeline
  - libplist
  - libpng
  - libproxy
  - libpsl
  - libpulse
  - libqaccessibilityclient
  - libqalculate
  - libqmi
  - libqrtr-glib
  - libraqm
  - libraw
  - libraw1394
  - librsvg
  - libsamplerate
  - libsasl
  - libseccomp
  - libsecret
  - libshout
  - libsidplay
  - libsm
  - libsndfile
  - libsodium
  - libsoup
  - libsoxr
  - libspectre
  - libsrtp
  - libssh
  - libssh2
  - libstemmer
  - libtasn1
  - libteam
  - libthai
  - libtheora
  - libtiff
  - libtirpc
  - libtommath
  - libtool
  - libunistring
  - libunwind
  - liburing
  - libusb
  - libusb-compat
  - libusbmuxd
  - libutempter
  - libva
  - libva-intel-driver
  - libva-mesa-driver
  - libva-vdpau-driver
  - libvdpau
  - libvisual
  - libvorbis
  - libvpx
  - libwacom
  - libwebp
  - libx11
  - libx86emu
  - libxau
  - libxaw
  - libxcb
  - libxcomposite
  - libxcrypt
  - libxcursor
  - libxdamage
  - libxdmcp
  - libxext
  - libxfixes
  - libxfont2
  - libxft
  - libxi
  - libxinerama
  - libxkbcommon
  - libxkbcommon-x11
  - libxkbfile
  - libxml2
  - libxmu
  - libxpm
  - libxrandr
  - libxrender
  - libxres
  - libxshmfence
  - libxslt
  - libxss
  - libxt
  - libxtst
  - libxv
  - libxxf86vm
  - libyaml
  - libyuv
  - libzip
  - licenses
  - lilv
  - linux510
  - linux510-nvidia
  - linux54-nvidia
  - linux-api-headers
  - linux-firmware
  - linux-latest
  - linux-latest-headers
  - linux-lts
  - linux-lts-headers
  - lirc
  - llvm-libs
  - lmdb
  - lm_sensors
  - logrotate
  - lsb-release
  - l-smash
  - lvm2
  - lz4
  - lzo
  - mailcap
  - man-db
  - manjaro-alsa
  - manjaro-application-utility
  - manjaro-base-skel
  - manjaro-browser-settings
  - manjaro-documentation-en
  - manjaro-firmware
  - manjaro-hello
  - manjaro-hotfixes
  - manjaro-icons
  - manjaro-kde-settings
  - manjaro-keyring
  - manjaro-pulse
  - manjaro-release
  - manjaro-settings-manager
  - manjaro-settings-manager-kcm
  - manjaro-settings-manager-knotifier
  - manjaro-system
  - manjaro-zsh-config
  - man-pages
  - md4c
  - mdadm
  - media-player-info
  - memtest86+
  - mesa
  - mesa-demos
  - mhwd
  - mhwd-amdgpu
  - mhwd-ati
  - mhwd-db
  - mhwd-nvidia
  - mhwd-nvidia-390xx
  - milou
  - minizip
  - mjpegtools
  - mkinitcpio
  - mkinitcpio-busybox
  - mkinitcpio-openswap
  - mobile-broadband-provider-info
  - modemmanager
  - modemmanager-qt
  - mpfr
  - mpg123
  - mtdev
  - mtpfs
  - nano
  - ncurses
  - ndctl
  - neon
  - nerd-fonts-noto-sans-mono
  - nettle
  - networkmanager
  - networkmanager-openconnect
  - networkmanager-openvpn
  - networkmanager-pptp
  - networkmanager-qt
  - networkmanager-vpnc
  - nfsidmap
  - nfs-utils
  - noto-fonts
  - noto-fonts-compat
  - npth
  - nspr
  - nss
  - nss-mdns
  - ntfs-3g
  - ntp
  - numlockx
  - oath-toolkit
  - okular
  - openal
  - openconnect
  - opencore-amr
  - openexr
  - openjpeg2
  - openmpi
  - openresolv
  - openssh
  - openssl
  - openvpn
  - opus
  - orc
  - os-prober
  - oxygen
  - oxygen-icons
  - p11-kit
  - p7zip
  - pacman
  - pacman-mirrors
  - pam
  - pamac-cli
  - pamac-common
  - pamac-gtk
  - pamac-tray-icon-plasma
  - pambase
  - pango
  - parted
  - partitionmanager
  - pciutils
  - pcre
  - pcre2
  - pcsclite
  - perl
  - perl-clone
  - perl-encode-locale
  - perl-error
  - perl-file-basedir
  - perl-file-desktopentry
  - perl-file-listing
  - perl-file-mimeinfo
  - perl-html-parser
  - perl-html-tagset
  - perl-http-cookies
  - perl-http-daemon
  - perl-http-date
  - perl-http-message
  - perl-http-negotiate
  - perl-io-html
  - perl-ipc-system-simple
  - perl-libwww
  - perl-lwp-mediatypes
  - perl-mailtools
  - perl-net-http
  - perl-parse-yapp
  - perl-timedate
  - perl-try-tiny
  - perl-uri
  - perl-www-robotrules
  - perl-xml-parser
  - perl-xml-writer
  - phonon-qt5
  - phonon-qt5-gstreamer
  - pinentry
  - pipewire
  - pixman
  - pkcs11-helper
  - pkgfile
  - plasma5-themes-breath2
  - plasma-desktop
  - plasma-framework
  - plasma-integration
  - plasma-nm
  - plasma-pa
  - plasma-simplemenu
  - plasma-systemmonitor
  - plasma-workspace
  - polkit
  - polkit-kde-agent
  - polkit-qt5
  - poppler
  - poppler-data
  - poppler-qt5
  - popt
  - portaudio
  - powerdevil
  - powertop
  - ppp
  - pptpclient
  - prison
  - procps-ng
  - protobuf
  - psmisc
  - pulseaudio
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - pulseaudio-ctl
  - pulseaudio-equalizer
  - pulseaudio-jack
  - pulseaudio-lirc
  - pulseaudio-qt
  - pulseaudio-rtp
  - pulseaudio-zeroconf
  - purpose
  - python
  - python-chardet
  - python-dnspython
  - python-docopt
  - python-gobject
  - python-idna
  - python-keyutils
  - python-markdown
  - python-npyscreen
  - python-pyqt5
  - python-pyqt5-sip
  - python-requests
  - python-urllib3
  - python-yaml
  - qca
  - qqc2-desktop-style
  - qrencode
  - qt5-base
  - qt5-declarative
  - qt5-graphicaleffects
  - qt5-imageformats
  - qt5-location
  - qt5-multimedia
  - qt5-quickcontrols
  - qt5-quickcontrols2
  - qt5-script
  - qt5-sensors
  - qt5-speech
  - qt5-svg
  - qt5-tools
  - qt5-virtualkeyboard
  - qt5-wayland
  - qt5-webchannel
  - qt5-webengine
  - qt5-x11extras
  - raptor
  - rav1e
  - re2
  - readline
  - reiserfsprogs
  - rest
  - rpcbind
  - rsync
  - rtkit
  - rtmpdump
  - ruby
  - rubygems
  - ruby-irb
  - ruby-reline
  - run-parts
  - samba
  - sbc
  - screenfetch
  - sddm
  - sddm-breath2-theme
  - sddm-kcm
  - sdl2
  - sed
  - serd
  - shadow
  - shared-mime-info
  - signond
  - signon-kwallet-extension
  - signon-plugin-oauth2
  - signon-ui
  - slang
  - smartmontools
  - smbclient
  - s-nail
  - snappy
  - socat
  - sof-firmware
  - solid
  - sonnet
  - sord
  - sound-theme-freedesktop
  - soundtouch
  - spandsp
  - spectacle
  - spectre-meltdown-checker
  - speex
  - speexdsp
  - sqlite
  - squashfs-tools
  - sratom
  - srt
  - sshfs
  - stoken
  - sudo
  - svt-av1
  - svt-hevc
  - syntax-highlighting
  - sysfsutils
  - systemd
  - systemd-fsck-silent
  - systemd-kcm
  - systemd-libs
  - systemd-sysvcompat
  - systemsettings
  - taglib
  - talloc
  - tar
  - tcl
  - tdb
  - terminus-font
  - tevent
  - texinfo
  - thin-provisioning-tools
  - threadweaver
  - tlp
  - tslib
  - ttf-dejavu
  - ttf-hack
  - twolame
  - tzdata
  - udiskie
  - udisks2
  - unarchiver
  - upower
  - usb_modeswitch
  - usbmuxd
  - usbutils
  - util-linux
  - util-linux-libs
  - v4l-utils
  - v86d
  - vi
  - vid.stab
  - vmaf
  - volume_key
  - vpnc
  - vte3
  - vte-common
  - vulkan-icd-loader
  - wavpack
  - wayland
  - wayland-protocols
  - web-installer-url-handler
  - webrtc-audio-processing
  - wget
  - which
  - wildmidi
  - wireless-regdb
  - wpa_supplicant
  - x264
  - x265
  - xapian-core
  - xcb-proto
  - xcb-util
  - xcb-util-cursor
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xdg-desktop-portal
  - xdg-desktop-portal-gtk
  - xdg-desktop-portal-kde
  - xdg-user-dirs
  - xdg-utils
  - xf86-input-elographics
  - xf86-input-evdev
  - xf86-input-libinput
  - xf86-input-void
  - xfsprogs
  - xkeyboard-config
  - xmlsec
  - xorg-fonts-encodings
  - xorg-mkfontscale
  - xorgproto
  - xorg-server
  - xorg-server-common
  - xorg-setxkbmap
  - xorg-twm
  - xorg-xauth
  - xorg-xdpyinfo
  - xorg-xinit
  - xorg-xkbcomp
  - xorg-xkill
  - xorg-xmessage
  - xorg-xmodmap
  - xorg-xprop
  - xorg-xrdb
  - xorg-xset
  - xorg-xsetroot
  - xvidcore
  - xxhash
  - xz
  - yakuake
  - zbar
  - zensu
  - zeromq
  - zimg
  - zita-alsa-pcmi
  - zita-resampler
  - zlib
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  - zsh-theme-powerlevel10k
  - zstd
  - zvbi
  - zxing-cpp
  - lib32-nvidia-utils
  - m4
  - manjaro-architect
  - manjaro-printer
  - manjaro-wallpapers-18.0
  - apparmor
  - appimagelauncher
  - autoconf
  - automake
  - nvidia-prime
  - nvidia-utils
  - pamac-flatpak-plugin
  - pamac-snap-plugin
  - skanlite
ignore_groups:
  - gnome
  - kde-applications
  - kde-graphics
  - kde-multimedia
  - kde-network
  - kde-system
  - kde-utilities
  - kf5
  - linux510-extramodules
  - linux54-extramodules
  - manjaro-tools
  - plasma
  - qt
  - qt5
  - xorg
  - xorg-apps
  - xorg-drivers
  - base-devel
