---
want:
  - 1password
  - ansible
  - aws-cli
  - aws-iam-authenticator-bin
  - bash-completion
  - bat
  - bfg
  - bind
  - bloomrpc
  - buf-bin
  - bwm-ng
  - calibre
  - cantata
  - ccid
  - cdrdao
  - cloc
  - dart
  - docker
  - docker-compose
  - dvd+rw-tools
  - emovix
  - etcher-bin
  - fail2ban
  - fd
  - fwupd
  - fzf
  - git-crypt
  - git-extras
  - go
  - goimports-git
  - golangci-lint-bin
  - google-chrome
  - google-cloud-sdk
  - gparted
  - graphviz
  - helm
  - hexyl
  - hibernator
  - insomnia-bin
  - iperf
  - jetbrains-toolbox
  - kernel-alive
  - kind-bin
  - kubectl
  - kustomize
  - lens-bin
  - libktorrent
  - libreoffice-fresh
  - logcli
  - minio
  - mosh
  - mpd
  - ncdu
  - neovim
  - net-tools
  - noto-fonts-cjk
  - noto-fonts-emoji
  - opensc
  - pacutils
  - podman
  - postgresql
  - python-pillow
  - python-pip
  - python-pyfuse3
  - python-pynvim
  - python-pysmbc
  - python-reportlab
  - qbittorrent
  - rancher-k3d-bin
  - restic
  - ripgrep
  - rust
  - skopeo
  - slack-desktop
  - steam-manjaro
  - strace
  - syncthing-bin
  - sysdig
  - sysstat
  - tailscale
  - terraform
  - timeshift
  - tmux
  - transcode
  - ttf-droid
  - ttf-inconsolata
  - ttf-indic-otf
  - ttf-liberation
  - ufw
  - vault
  - vcdimager
  - visual-studio-code-bin
  - vlc
  - wireguard-tools
  - wl-clipboard
  - xclip
  - xsel
  - yarn
  - yay
  - yq
ignore:
- acpi
- acpid
- alsa-firmware
- alsa-utils
- amd-ucode
- android-tools
- android-udev
- apparmor
- appimagelauncher
- avahi
- b43-fwcutter
- bash
- btrfs-progs
- bzip2
- cdparanoia
- coreutils
- cpupower
- crda
- cronie
- cryptsetup
- device-mapper
- dhclient
- dhcpcd
- diffutils
- dmidecode
- dmraid
- dnsmasq
- dosfstools
- e2fsprogs
- ecryptfs-utils
- efibootmgr
- f2fs-tools
- ffmpeg
- filesystem
- firefox
- gcc-libs
- glibc
- gnome-icon-theme
- gst-libav
- gst-plugins-bad
- gst-plugins-base
- gst-plugins-good
- gst-plugins-ugly
- gtk3
- htop
- illyria-wallpaper
- inetutils
- intel-ucode
- inxi
- iproute2
- iputils
- jfsutils
- kaccounts-providers
- less
- lib32-nvidia-utils
- libcanberra
- libcanberra-gstreamer
- libcanberra-pulse
- libdvdcss
- libva-intel-driver
- libva-mesa-driver
- libva-vdpau-driver
- licenses
- linux-latest
- linux-latest-headers
- linux-lts
- linux-lts-headers
- logrotate
- lvm2
- man-db
- man-pages
- manjaro-alsa
- manjaro-application-utility
- manjaro-architect
- manjaro-browser-settings
- manjaro-documentation-en
- manjaro-firmware
- manjaro-hello
- manjaro-hotfixes
- manjaro-kde-settings
- manjaro-printer
- manjaro-pulse
- manjaro-release
- manjaro-settings-manager-kcm
- manjaro-settings-manager-knotifier
- manjaro-system
- manjaro-wallpapers-18.0
- manjaro-zsh-config
- mdadm
- memtest86+
- mesa-demos
- mhwd
- mhwd-db
- mkinitcpio-openswap
- mobile-broadband-provider-info
- modemmanager
- mtpfs
- nano
- networkmanager-openconnect
- networkmanager-openvpn
- networkmanager-pptp
- networkmanager-vpnc
- nfs-utils
- noto-fonts
- nss-mdns
- ntfs-3g
- ntp
- numlockx
- nvidia-prime
- nvidia-utils
- openresolv
- openssh
- os-prober
- p7zip
- pamac-cli
- pamac-flatpak-plugin
- pamac-gtk
- pamac-snap-plugin
- pamac-tray-icon-plasma
- pciutils
- perl
- perl-file-mimeinfo
- perl-uri
- phonon-qt5-gstreamer
- pkgctrl-bin
- plasma-simplemenu
- poppler-data
- powertop
- procps-ng
- psmisc
- pulseaudio-bluetooth
- pulseaudio-ctl
- pulseaudio-zeroconf
- python-pyqt5
- reiserfsprogs
- rsync
- ruby
- s-nail
- samba
- screenfetch
- sddm
- sddm-breath2-theme
- shadow
- skanlite
- snapd
- snapd-glib
- spectre-meltdown-checker
- sshfs
- sysfsutils
- system-config-printer
- systemd
- systemd-boot-manager
- systemd-fsck-silent
- systemd-kcm
- systemd-sysvcompat
- tar
- terminus-font
- tlp
- ttf-dejavu
- udiskie
- udisks2
- unarchiver
- usb_modeswitch
- usbutils
- util-linux
- vi
- wallpapers-2018
- wallpapers-juhraya
- wget
- wpa_supplicant
- xdg-desktop-portal
- xdg-user-dirs
- xdg-utils
- xf86-input-elographics
- xfsprogs
- xorg-twm
- xorg-xinit
- xz
- zensu
ignore_groups:
  - gnome
  - kde-applications
  - kde-graphics
  - kde-multimedia
  - kde-network
  - kde-system
  - kde-utilities
  - kf5
  - linux510-extramodules
  - linux54-extramodules
  - manjaro-tools
  - plasma
  - qt
  - qt5
  - xorg
  - xorg-apps
  - xorg-drivers
  - base-devel
